# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lu Mizinski
email: luciana@tilia.com.br
description: > # this means to ignore newlines until "baseurl:"
  Educação, tecnologia e esporte.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lumizinski.github.io/" 
twitter_username: lumizinski
github_username:  lumizinski

# Build settings
markdown: kramdown
